z version: '3'

services:
  backend: 
    image: wlguss/inspire-monolithic
    container_name: monolithic-backend-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/inspire
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1215
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_SHOW_SQL: true
    restart: always
    links: 
      - database
    depends_on:
      - database
  database:
    image: wlguss/inspire-mariadb
    container_name: monolithic-maraidb-container
    ports:
      - "6033:3306"
    environment:
      MARIADB_USER: root
      MARIADA_ROOT_PASSWORD: 1215
      MARIADB_DATABASE: inspire
  redis: 
    image: wlguss/inspire-redis
    container_name: monolithic-redis-container